# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 553)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_title = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_title.setObjectName("txt_title")
        self.gridLayout.addWidget(self.txt_title, 0, 0, 1, 1)
        self.st_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.st_widget.setObjectName("st_widget")
        self.edit = QtWidgets.QWidget()
        self.edit.setObjectName("edit")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.edit)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_main = QtWidgets.QPlainTextEdit(self.edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_main.sizePolicy().hasHeightForWidth())
        self.txt_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setKerning(False)
        self.txt_main.setFont(font)
        self.txt_main.setAutoFillBackground(False)
        self.txt_main.setStyleSheet("")
        self.txt_main.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_main.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.txt_main.setPlainText("")
        self.txt_main.setObjectName("txt_main")
        self.horizontalLayout.addWidget(self.txt_main)
        self.st_widget.addWidget(self.edit)
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.search)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tr_search = QtWidgets.QTreeView(self.search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tr_search.sizePolicy().hasHeightForWidth())
        self.tr_search.setSizePolicy(sizePolicy)
        self.tr_search.setObjectName("tr_search")
        self.gridLayout_2.addWidget(self.tr_search, 0, 0, 1, 1)
        self.v_layout_cb = QtWidgets.QVBoxLayout()
        self.v_layout_cb.setObjectName("v_layout_cb")
        self.checkBox = QtWidgets.QCheckBox(self.search)
        self.checkBox.setObjectName("checkBox")
        self.v_layout_cb.addWidget(self.checkBox)
        self.gridLayout_2.addLayout(self.v_layout_cb, 0, 1, 1, 1)
        self.st_widget.addWidget(self.search)
        self.view = QtWidgets.QWidget()
        self.view.setObjectName("view")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.view)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.web_view = QtWebEngineWidgets.QWebEngineView(self.view)
        self.web_view.setObjectName("web_view")
        self.horizontalLayout_5.addWidget(self.web_view)
        self.st_widget.addWidget(self.view)
        self.gridLayout.addWidget(self.st_widget, 1, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.st_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notes"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))

from PyQt5 import QtWebEngineWidgets
